# Use the official Python image as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script into the container
COPY demo.py /app

# Command to run the Python script
CMD ["python", "demo.py"]

